name: Build EXE for Girlfriend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4       # 保持 v4

    - name: Set up Python
      uses: actions/setup-python@v5   # 保持 v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --name="LoveToolbox" --windowed --onefile --clean --noconfirm main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 保持 v4，这是关键
      with:
        name: LoveToolbox_EXE
        path: dist/LoveToolbox.exe
