name: Build EXE for Girlfriend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4       # 正确

    - name: Set up Python
      uses: actions/setup-python@v5   # 正确
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --name="LoveToolbox" --windowed --onefile --clean --noconfirm main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 正确
      with:
        name: LoveToolbox_EXE
        path: dist/LoveToolbox.exe
      
    - name: Upload to WeTransfer
      shell: bash                       # <--- 必须加这一行！切换到 Bash 环境
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet -s --no-progress dist/LoveToolbox.exe
